"""Markdown exporter for research results."""
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

from pydantic import BaseModel

from config import config


class ResearchSection(BaseModel):
    """A section in the research report."""

    title: str
    content: str
    subsections: List["ResearchSection"] = []


class ResearchReport(BaseModel):
    """Complete research report."""

    subject: str  # Character name or work title
    subject_type: str  # "character", "work", etc.
    summary: str
    sections: List[ResearchSection]
    sources: List[str] = []
    metadata: Dict[str, Any] = {}
    created_at: datetime = datetime.now()


class MarkdownExporter:
    """Export research reports to Markdown format."""

    def __init__(self, output_dir: Optional[Path] = None):
        """Initialize the exporter.

        Args:
            output_dir: Directory to save markdown files (defaults to config)
        """
        self.output_dir = output_dir or config.outputs_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export(self, report: ResearchReport) -> Path:
        """Export a research report to a markdown file.

        Args:
            report: The ResearchReport to export

        Returns:
            Path to the created markdown file
        """
        # Create filename
        safe_name = self._sanitize_filename(report.subject)
        timestamp = report.created_at.strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_name}_{timestamp}.md"
        filepath = self.output_dir / filename

        # Build markdown content
        markdown = self._build_markdown(report)

        # Write to file
        filepath.write_text(markdown, encoding="utf-8")

        return filepath

    def _build_markdown(self, report: ResearchReport) -> str:
        """Build markdown content from a report.

        Args:
            report: The ResearchReport

        Returns:
            Markdown formatted string
        """
        lines = []

        # Title
        lines.append(f"# {report.subject}")
        lines.append("")

        # Metadata
        lines.append("---")
        lines.append(f"**Type:** {report.subject_type}")
        lines.append(f"**Research Date:** {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}")
        if report.metadata:
            for key, value in report.metadata.items():
                lines.append(f"**{key.title()}:** {value}")
        lines.append("---")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(report.summary)
        lines.append("")

        # Sections
        for section in report.sections:
            self._add_section(lines, section, level=2)

        # Sources
        if report.sources:
            lines.append("## Sources")
            lines.append("")
            for i, source in enumerate(report.sources, 1):
                lines.append(f"{i}. {source}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Research Agent on {report.created_at.strftime('%Y-%m-%d')}*")

        return "\n".join(lines)

    def _add_section(
        self,
        lines: List[str],
        section: ResearchSection,
        level: int = 2,
    ) -> None:
        """Add a section to the markdown lines.

        Args:
            lines: List of markdown lines to append to
            section: The section to add
            level: Heading level (2 = ##, 3 = ###, etc.)
        """
        # Add section heading
        heading = "#" * level
        lines.append(f"{heading} {section.title}")
        lines.append("")

        # Add section content
        lines.append(section.content)
        lines.append("")

        # Add subsections recursively
        for subsection in section.subsections:
            self._add_section(lines, subsection, level=level + 1)

    def _sanitize_filename(self, name: str) -> str:
        """Sanitize a string for use as a filename.

        Args:
            name: The string to sanitize

        Returns:
            Sanitized filename
        """
        # Replace invalid characters
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            name = name.replace(char, "_")

        # Limit length
        if len(name) > 100:
            name = name[:100]

        return name


def create_sample_report(subject: str = "테스트 캐릭터") -> ResearchReport:
    """Create a sample research report for testing.

    Args:
        subject: Subject name

    Returns:
        Sample ResearchReport
    """
    return ResearchReport(
        subject=subject,
        subject_type="character",
        summary=f"{subject}에 대한 종합적인 리서치 결과입니다. 다양한 소스를 통해 수집된 정보를 정리했습니다.",
        sections=[
            ResearchSection(
                title="기본 정보",
                content=f"{subject}의 기본 프로필과 배경 정보입니다.",
                subsections=[
                    ResearchSection(
                        title="외형",
                        content="외형적 특징에 대한 설명입니다.",
                    ),
                    ResearchSection(
                        title="성격",
                        content="성격과 특징에 대한 설명입니다.",
                    ),
                ],
            ),
            ResearchSection(
                title="팬 반응",
                content="SNS와 커뮤니티에서의 팬 반응을 정리했습니다.",
            ),
        ],
        sources=[
            "https://namu.wiki/w/테스트",
            "Twitter: @example",
            "Google Search Results",
        ],
        metadata={"original_work": "테스트 작품", "author": "작가명"},
    )
